services:
  foobar:
    build: .
    volumes:
      - ./in:/in
      - ./out:/out
      - ./src:/src
    # for development bind to juyper
    #ports:
    #  - 8888:8888
    # command: ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
    # production
    environment:
      TOOL_RUN: foobar
    command: ["python",  "run.py"]
    