services:

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metacatalog
    expose:
      - 5432
    ports:
      - 5445:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 1s
      timeout: 1s
      retries: 5

  data-loader:
    build: .
    volumes:
      - ./in:/in
      - ./out:/out
      - ./data/files:/data
      - ./src:/src
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      METACATALOG_URI: postgresql://postgres:postgres@db:5432/metacatalog
      TOOL_RUN: ismn_loader
    # command: ["echo",  "run the loader with an active MetaCatalog instance like: 'docker compose run --rm data-loader python run.py'"] 
    ports:
     - 8000:8000
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8000", "--no-browser", "--allow-root", "--NotebookApp.token='dev'"]


  stable-ranks:
    build: .
    volumes:
      - ./workflow/loader/out:/in
      - ./workflow/rank_analysis/out:/out
      - ./src:/src
      - type: bind
        source: ./workflow/rank_analysis/in/input.json
        target: /in/input.json
        read_only: true
    # for development bind to juyper
    # ports:
    #  - 8000:8000
    # command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8000", "--no-browser", "--allow-root"]
    # production
    environment:
      TOOL_RUN: ranks
    command: ["echo",  "run the loader with an active MetaCatalog instance like: 'docker compose run --rm ranks python run.py'"]
    